'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faPeopleGroup, faCapsules, faSuitcase, faBookMedical, faTriangleExclamation,
  faGear, faSearch, faSignOutAlt, faUser
} from '@fortawesome/free-solid-svg-icons';

import ModalEmergencia from './global/ModalEmergencia'
import { signOut } from "next-auth/react";
import LogoContigo from './LogoContigo';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="layout">
      <aside className="sidebar">
        <header className="sidebar-image">
          <a href="/">
            <LogoContigo style={{ width: "100%", height: "auto", maxHeight: "60px" }} />
          </a>
        </header>
        <nav className="sidebar-list">
          <ul>
            <li>
              <a href="/familiares">
                <FontAwesomeIcon icon={faPeopleGroup} size="sm" /> Familiares
              </a>
            </li>
            <li>
              <a href="/usuarios">
                <FontAwesomeIcon icon={faUser} size="sm" /> Usuarios
              </a>
            </li>
            <li>
              <a href="/medicamentos">
                <FontAwesomeIcon icon={faCapsules} size="sm" /> Medicamentos
              </a>
            </li>
            <li>
              <a href="/sintomas">
                <FontAwesomeIcon icon={faSuitcase} size="sm" /> Síntomas
              </a>
            </li>
            <li>
              <a href="/historial">
                <FontAwesomeIcon icon={faBookMedical} size="sm" /> Historial
              </a>
            </li>
            <li>
              <a href="/datos-criticos">
                <FontAwesomeIcon icon={faTriangleExclamation} size="sm" /> Datos críticos
              </a>
            </li>
          </ul>
        </nav>
        <footer className="sidebar-profile">
          <div className="profile-icons">
            <a href="#">
              <FontAwesomeIcon icon={faGear} size="sm" />
            </a>
            <a href="#">
              <FontAwesomeIcon icon={faSearch} size="sm" />
            </a>
            <a href="#" onClick={() => signOut({ callbackUrl: "/login" })} >
              <FontAwesomeIcon icon={faSignOutAlt} size="sm" />
            </a>
          </div>
          <ModalEmergencia />

          <div className="profile-action">
            <a href="/contacto-emergencia">
              <FontAwesomeIcon icon={faUser} size="sm" />Perfil
            </a>
          </div>
        </footer>
      </aside>
      <main className="contenido">
        <header className="navbar"></header>
        <>{children}</>
        <footer className="footer"></footer>
      </main>
    </div>
  );
}
